import { Construct } from "constructs";
import { Environnment } from "../environment";
import { LogAnalyticsWorkspace } from "@cdktf/provider-azurerm/lib/log-analytics-workspace";
import { ApplicationInsights } from "@cdktf/provider-azurerm/lib/application-insights";
import { monitorSmartDetectorAlertRule } from "@cdktf/provider-azurerm";
import { MonitorSmartDetectorAlertRule } from "@cdktf/provider-azurerm/lib/monitor-smart-detector-alert-rule";
import { MonitorActionGroup } from "@cdktf/provider-azurerm/lib/monitor-action-group";

export class SuperBusInsights extends Construct {

  private readonly applicationInsights: ApplicationInsights;

  constructor(scope: Construct, environment: Environnment) {
    super(scope, environment.formatName('cdktf', 'insights'));

    const logAnalyticsWorkspace = new LogAnalyticsWorkspace(this, environment.formatName('log'), {
      name: environment.formatName('log'),
      location: environment.location,
      resourceGroupName: environment.resourceGroup,
      sku: 'PerGB2018',
      retentionInDays: 30,
      dailyQuotaGb: 10,
    });

    this.applicationInsights = new ApplicationInsights(this, environment.formatName('appi'), {
      name: environment.formatName('appi'),
      location:  environment.location,
      resourceGroupName: environment.resourceGroup,
      retentionInDays: 30,
      dailyDataCapInGb: 10,
      applicationType: 'web',
      workspaceId: logAnalyticsWorkspace.id,
    });

    // Normally, Azure automatically creates an action group when creating the Application Insights resource.
    // This can cause issue when destroying the resources.
    // We manually create an action group with the same name.
    // See https://github.com/hashicorp/terraform-provider-azurerm/issues/18026.
    // new MonitorActionGroup(this, environment.formatName('ag', 'smart-detect'), {
    //   resourceGroupName: environment.resourceGroup,
    //   name: 'Application Insights Smart Detection',
    //   shortName: 'SmartDetect',
    //   enabled: false,
    // });

    // The application_insights-> disable_generated_rule causes the provider to just
    // wait for 10 minutes until Azure has created the smart detection rule in the background
    // and then disable it. We instead just create a rule with the same expected name
    // immediately.
    new MonitorSmartDetectorAlertRule(this, environment.formatName('alert'), {
      // Name generated by Azure Failure Anomalies - appi-superbus-cmdev
      name: `Failure Anomalies - ${this.applicationInsights.name}`,
      resourceGroupName: environment.resourceGroup,
      detectorType: 'FailureAnomaliesDetector',
      enabled: false,
      scopeResourceIds: [this.applicationInsights.id],
      frequency: 'PT1M',
      severity: 'Sev3',
      actionGroup: {
        ids: [],
      },
    })
  }

  get connection(): string {
    return this.applicationInsights.connectionString;
  }
}
