using Azure.Storage.Blobs;
using Dbosoft.Bote.Primitives;
using Rebus.DataBus;
using Rebus.Logging;
using Rebus.Messages;
using Rebus.Pipeline;

namespace Dbosoft.Bote.Rebus.Integration.Pipeline;

[StepDocumentation("Imports DataBus attachments from clients via SAS URL to cloud's IDataBusStorage")]
internal class DataBusIncomingStep(
    IDataBusStorage dataBusStorage,
    IRebusLoggerFactory loggerFactory)
    : IIncomingStep
{
    private readonly ILog _logger = loggerFactory.GetLogger<DataBusIncomingStep>();

    public async Task Process(IncomingStepContext context, Func<Task> next)
    {
        var transportMessage = context.Load<TransportMessage>();

        // Check for cloud-inbox SAS URL header (generated by BoteWorker)
        if (!transportMessage.Headers.TryGetValue(BoteHeaders.DataBusInboxSas, out var sasUrl))
        {
            await next();
            return;
        }

        // Get attachment ID from header
        if (!transportMessage.Headers.TryGetValue(BoteHeaders.AttachmentId, out var attachmentId))
        {
            _logger.Error("Message has cloud-inbox-sas header but missing attachment ID");
            throw new InvalidOperationException("Message has SAS URL but no attachment ID header");
        }

        var tenantId = transportMessage.Headers[BoteHeaders.TenantId];

        _logger.Info("Importing attachment {AttachmentId} from cloud inbox for tenant {TenantId}",
            attachmentId, tenantId);

        // Download from SAS URL (storage-agnostic!)
        var blobClient = new BlobClient(new Uri(sasUrl));

        // Get blob properties to read metadata (metadata is already on the blob from DataBusCopyProcessor)
        var sourceProps = await blobClient.GetPropertiesAsync();

        // Filter out internal Bote metadata keys, keep user-defined metadata
        var metadata = BoteStorageConstants.Metadata.FilterUserMetadata(sourceProps.Value.Metadata);

        // Add required Bote metadata
        metadata[BoteStorageConstants.Metadata.TenantId] = tenantId;

        await using var stream = await blobClient.OpenReadAsync();
        await dataBusStorage.Save(attachmentId, stream, metadata);

        _logger.Info("Successfully imported attachment {AttachmentId} to cloud DataBus", attachmentId);

        // Cleanup cloud inbox after import
        await blobClient.DeleteIfExistsAsync();

        // Remove headers
        transportMessage.Headers.Remove(BoteHeaders.DataBusInboxSas);
        transportMessage.Headers.Remove(BoteHeaders.AttachmentId);

        await next();
    }
}
